### ISSUE TITLE
USB, SD connectors naming scheme

### ISSUE THREAD

**Issue by swiftgeek** [KiCad/Connectors.pretty#21]
I would like to push few more footprints for sockets to this repo (all "ebay" variants):
- usb 3.0 micro B, bottom mounted, smt
- usb 2.0 micro B, mid mount smt (here i might have additional issues with how such parts should look like)
- usb 2.0 micro B, bottom mounted, smt (as oposed to hybrid (smt+tht) available in this repo)
- usb 2.0 A smt http://pic01.uxsight.com/photo_new/20130813/c/ux_a13081300ux0333_ux_c.jpg
- microSD, self eject, TFP09-2-12B

So some renaming is most likely needed to existing parts eg.:
- µUSB sockets:
  Micro USB 2.0 - B - SMT/THT/Hybrid - Top/Bottom/MidMount
  http://gct.co/usb-connectors/images/micro-usb-mount-types.jpg
- SD - can be SelfEject/PushPush, Hinged, Push-Pull, and more (here mostly clarification is needed on what name should be used for types as there are many different names used by different retailers)
- For USB A sockets i don't even have slightest idea as they come in many shapes and mount types (often hybrid)

Also what is the naming convention for adding another variant of perfectly named part? Just add a number and increment? (especially when vendor/model is unknown)

**Comment by nickoe** [comment]
@CarlPoirier or @ricardocrudo I am just bumping this in case you did not follow this repo.

**Comment by ricardocrudo** [comment]
Currently connect lib holds all types of connectors (SMD, PTH,...) maybe in the future it might be split off. Until this does not happen and to make easy to track them later, you could add the mounting-type in the footprint name (SMT/THT/Hybrid) and also append other informations (SelfEject/PushPush/...). You can get some thought about name convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.
