### ISSUE TITLE
Drill hole correction in USB-Mini-B footprint

### ISSUE THREAD

**Issue by hexagon5un** [KiCad/Connectors.pretty#4]
Hi,

I was building a part with a mini-b usb connector, and the DRC was giving me an error b/c the drill hole wasn't electrically connected to pin 2.  I thought that was odd, and fixed it up.  

In the process, a couple of other lines got changed in the source file.  I'm not entirely sure what happened there, but I submitted a pull request anyway.  I believe the meat of the change is just removing "2" from the drill hole.  If the rest is unnecessary, feel free to cherry pick.  

Best, 
  Elliot.

**Comment by hackscribble** [comment]
Closing historic issue.
