### ISSUE TITLE
Error of holes positions in DB connectors (D-Sub)

### ISSUE THREAD

**Issue by mavati** [KiCad/Connectors.pretty#44]
Hello everybody.

The 2 holes in many common DB connectors right-angled (DB9MC/DB9FC/DB15MC/DB15FC/DB25MC/DB25FC) are miss-aligned: too high, they should be placed in the middle of the 2 ranges of pins (it seems ok only in the DB37FC footprint).
Else the length of the connector is different on many models (EU, US, Asia, ...). Perhaps, theses connectors should be renamed with the length added or model family (EU, US) (so that people know that it can be different... to avoid bad surprise!) - but if length, which length ? (border to holes, or to first pins range) ;-)
![db9_right_angle_harting_2](https://cloud.githubusercontent.com/assets/22594367/19050337/6e7c2f84-89ae-11e6-8c52-f01a8855add7.png)

Best regards.

PS: in reference messages on this forum : https://forum.kicad.info/t/error-in-d-sub-footprints-holes-positions/4099

**Comment by SchrodingersGat** [comment]
I am closing this issue for now - any further issues with the DSUB footprints should be directed to https://github.com/kicad/connectors_dsub.pretty
