### ISSUE TITLE
RJ45_8.kicad_mod NPTH holes too far

### ISSUE THREAD

**Issue by leventelist** [KiCad/Connectors.pretty#49]
The distance between NPTH holes shall be 11.43 mm.

Specs here:

http://www.molex.com/pdm_docs/sd/955407886_sd.pdf

(sorry, I couldn't find the version without shield)

My (corrected) version:

[RJ45.kicad_mod.txt](https://github.com/KiCad/Connectors.pretty/files/643808/RJ45.kicad_mod.txt)

**Comment by leventelist** [comment]
Other minor discrepancies discovered with the RJ45 connector. The correct footprint is attached.

I found the right specification:

http://www.molex.com/molex/products/datasheet.jsp?part=active/0955012881_MODULAR_JACKS_PLUG.xml&channel=Products&Lang=en-US

[RJ45.kicad_mod.txt](https://github.com/KiCad/Connectors.pretty/files/644424/RJ45.kicad_mod.txt)

**Comment by jkriege2** [comment]
Could you alter the footprint, make it conform to KLC (if it doesn't yet, see https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) and post a PullRequest to fix this?

Best,
JAN

**Comment by SchrodingersGat** [comment]
We have now marked this repository as read-only, and new footprint contributions must be made to https://github.com/kicad/kicad-footprints
