### ISSUE TITLE
Footprints for tab / quick disconect / faston PCB-mount terminals?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/Connectors.pretty#56]
I don't see any of this type of terminal in any connector library. Are they there are I'm just missing them? If not, I'd like to create the footprints and submit a PR.

Since the naming seems to vary quite a bit, here's a picture of the terminal in question:
http://www.kangyang.com/Link_Photo/2120-000.jpg

I'm most familiar with seeing 0.187", 0.205", and 0.250" blade widths in a couple of varieties of hole size.

So then I have two questions:
- What name should this footprint family have? We need to pick some footprint naming convention for KiCad even if the industry has many names.
- Which library does it go in? Connectors.pretty sounds good to me, but maybe there's a better choice?

@jkriege2 Maybe you have some input?

**Comment by jkriege2** [comment]
I would add them to `Connectors.pretty` ... and I think that would be a great addition. Here's an overview: http://www.produktinfo.conrad.com/datenblaetter/800000-824999/808428-in-01-en-6_3_FASTON_FLACHSTECKER_FUER_LP.pdf

... then maybe also these would be nice to have ;-) ... this way it may become a little-finger-full-hand-thing ;-)
http://www.produktinfo.conrad.com/datenblaetter/525000-549999/526191-da-01-ml-SORTIMENT_KONTAKTSTIFTE_de_en_fr.pdf
http://www.produktinfo.conrad.com/datenblaetter/525000-549999/527866-da-01-ml-LOETSTIFTE_de_en_fr.pdf

About naming ... not really an idea ... maybe `PIN_FASTON_250Series_Pitch5.08mm`, `PIN_FASTON_250Series_Pitch5.08mm_Angled`, `PIN_FASTON_187Series_Pitch5.08mm`, `PIN_FASTON_187Series_Pitch5.08mm_Angled`, ... and `PIN_D1.3mm`, `PIN_D1.0mm`, ...

What do you think?
JAN

**Comment by evanshultz** [comment]
As `FASTON` appears to be a trademarked named by AMP, I think we're best to use another name. `Quick disconnect` seems popular, but because it's shorter and also common I'm proposing we use `Tab`.

My naming convention is like so: `Tab[_<blade number>]_<blade width>_<pin number>_<orientation>[_<feature>]`. Examples: `Tab_250_2P_Vert`, `Tab_187_2P_Vert_Feet` (for a tab with bent ends to support it against the PCB surface), `Tab_250_2P_Angled`, `Tab_Dual_187_2P_Vert` (for the U-shaped style).

I'm not worrying about tab thickness since a thinner one can be used with the same drill diameter as long as the pins are roughly the same size. And the same board hole size is given regardless of tab thickness. In the past I've used different drill hole sizes due to differences in blade thickness, pin shape (loose versus AI), and wave soldering machinery, but here I think a one-size-fits-99% approach will work.

If this seems like a reasonable approach I'll get started. Thanks for your comments, Jan!

For the other part styles, which I didn't fully try to ensure fit into the above naming scheme, I'll work on them later as time and/or need allow.

**Comment by evanshultz** [comment]
Here's an example footprint for a vertical tab with 250mil blade width. Any feedback? (Pardon the formatting.)

> (module Tab_250_2P_Vert (layer F.Cu) (tedit 58964DA3)
  (descr "Through hole pin header")
  (tags "pin header")
  (fp_text reference REF** (at 2.5 -2) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value Tab_250_2P_Vert (at 2.5 2) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start 6.56 -0.405) (end 6.56 0.405) (layer F.SilkS) (width 0.12))
  (fp_line (start 1.48 0.465) (end 3.6 0.465) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.48 -0.405) (end -1.48 0.405) (layer F.SilkS) (width 0.12))
  (fp_line (start 3.6 -0.465) (end 1.48 -0.465) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.42 0.405) (end -1.42 -0.405) (layer F.Fab) (width 0.1))
  (fp_line (start 6.5 0.405) (end -1.42 0.405) (layer F.Fab) (width 0.1))
  (fp_line (start 6.5 -0.405) (end 6.5 0.405) (layer F.Fab) (width 0.1))
  (fp_line (start -1.42 -0.405) (end 6.5 -0.405) (layer F.Fab) (width 0.1))
  (fp_line (start -1.8 -1.4) (end -1.8 1.4) (layer F.CrtYd) (width 0.05))
  (fp_line (start 6.8 -1.4) (end 6.8 1.4) (layer F.CrtYd) (width 0.05))
  (fp_line (start -1.8 -1.4) (end 6.8 -1.4) (layer F.CrtYd) (width 0.05))
  (fp_line (start -1.8 1.4) (end 6.8 1.4) (layer F.CrtYd) (width 0.05))
  (pad 1 thru_hole circle (at 0 0) (size 2.1 2.1) (drill 1.4) (layers *.Cu *.Mask F.SilkS))
  (pad 2 thru_hole circle (at 5.08 0) (size 2.1 2.1) (drill 1.4) (layers *.Cu *.Mask F.SilkS))
)

**Comment by jkriege2** [comment]
Hi!

looks good to me ... but please note that you have F.SilkS actiavted for the pads!

best,
JAN

**Comment by evanshultz** [comment]
Thank you, Jan. Closing issue and will submit PR.
