### ISSUE TITLE
 Connectors.pretty/PINTST.kicad_mod - hole too small

### ISSUE THREAD

**Issue by John-Nagle** [KiCad/Connectors.pretty#60]
This "PINTST" footprint has an 0.63mm hole. There is no real-world test pin that small known to DigiKey or Mouser.  1.00 or 1.03mm is the smallest size in standard through-hole test pins.

The 3D model "Connect.3dshapes/PINTST.wrl", which looks like an undersized 1-pin header in blue, fits the 0.63 hole. It should be resized or replaced with some real part. 

(I sent a board to fab using this footprint, assuming I could order a matching test pin. Oops. If anyone knows of a real-world 0.63mm test pin, let me know.)

**Comment by jkriege2** [comment]
Then why not post a modified footprint that we can incorporate into the lib?
JAN

**Comment by SchrodingersGat** [comment]
e.g. https://cdn.harwin.com/pdfs/P13-XX23.pdf 

That's 0.68mm

**Comment by SchrodingersGat** [comment]
Is that the sort of pin you mean?

**Comment by John-Nagle** [comment]
No, that Harwin part is a spring-loaded pin for a bed-of-nails test fixture, not something you put in a PC board to allow attaching a test probe.

**Comment by SchrodingersGat** [comment]
Ok, I misunderstood :)

**Comment by jkriege2** [comment]
Hi!

I'm closing this, since we now have a library of solder pins:
https://github.com/KiCad/Connectors.pretty/pull/86

and a sensible library of testpoints:
https://github.com/KiCad/Connectors_TestPoints.pretty

Best,
JAN
