### ISSUE TITLE
Parse Error loading lib from lib wizard

### ISSUE THREAD

**Issue by rivimey** [KiCad/Connectors.pretty#66]
Just tried to refresh my local libs from github using the library wizard, and consistently got this error, which caused the whole procedure to fail:

Error: PARSE_ERROR: Expecting 'circle, rectangle, oval or trapezoid' in input/source 'https://github.com/KiCad/Connectors.pretty' line 34 offset 14.

I was able to refresh the other libraries only by omitting the update on this one.

KiCad Stable 4.0.5 Mac OS running on El Capitan. Loaded Librarian from within a project.

![screen shot 2017-03-10 at 18 00 54](https://cloud.githubusercontent.com/assets/1536678/23807758/d0c21d66-05be-11e7-8fea-758f546181f8.png)

**Comment by bobc** [comment]
Someone has pushed a module that uses roundrect pad type, this is not yet supported in 4.0.x (the offending module is SMA_SMD_Jack_Straight.kicad_mod).

**Comment by tomb7** [comment]
I cannot even list footprints with this.
How can I work around this?

 Tom

**Comment by bobc** [comment]
I think the simplest workaround is to download the library to your PC and use it locally.

**Comment by tomb7** [comment]
I am a bit surprised that someone from around the world was able to cripple my afternoon.
Obviously I have to become more of an expert on setting this up.

**Comment by aewallin** [comment]
I get the same error with 4.0.6-e0 on Ubuntu 16.04.01

**Comment by jkriege2** [comment]
fix is merged: https://github.com/KiCad/Connectors.pretty/pull/68

**Comment by gauravjuvekar** [comment]
Whoops. I was running nightly and forgot to test from stable. Sorry.
