### ISSUE TITLE
bornier 3d models are misaligned

### ISSUE THREAD

**Issue by v01d** [KiCad/Connectors.pretty#75]
![image](https://user-images.githubusercontent.com/161706/27439570-9cddfe6c-573e-11e7-9654-0d73d26b2d2c.png)

**Comment by poeschlr** [comment]
Do you have the newest 3d files?

3d files are not updated automatically. Footprints are.
This means if we fix the footprint and or 3d model, you will only get the new footprint.
Yes we know this is bad. The nightly build version already includes a 3d files downloader so keeping the footprint lib and 3d model lib in synch will be a lot easier in future releases of kicad.

For now your only option is to either clone the library repo or download the files.
Either clone the [main lib repo](https://github.com/KiCad/kicad-library/tree/master/modules/packages3d) or the new [packages3d repo](https://github.com/KiCad/packages3D). The later only includes reworked 3d files that supply step models as well as wrl files.

These 3d files either need to be placed in the directory where KISYS3DMOD currently points to (somewhere under c: for windows, in /usr/share/kicad/modules/packages3d/ for linux)
Or place the files wherever you want and change where KISYS3DMOD points to (kicad main window->preferences->configure paths)

**Comment by v01d** [comment]
Yes, I have everything from git. Could you try opening the bornier2
footprint  on the 3D viewer?

**Comment by poeschlr** [comment]
You are right. Care to fix it?
(If you are really motivated, it would be great if the footprints would be reworked completely. At least give an english documentation and a link to an english datasheet in the documentation field, add a second reference on fab as well as pin 1 markers on fab and silk.)

**Comment by v01d** [comment]
It is a bit difficult for me right now to make a proper patch, but it seems
the fix for the offset is simple. It needs an X offset to the 3D shape of
(k-1)*0.1, where k is the number of pins of the bornier (ie: bornier2 needs
0.1, bornier3 needs 0.2, etc)

**Comment by SchrodingersGat** [comment]
We have now marked this repository as read-only, and new footprint contributions must be made to https://github.com/kicad/kicad-footprints
