### ISSUE TITLE
RFC: Connector library names

### ISSUE THREAD

**Issue by evanshultz** [KiCad/Connectors.pretty#83]
Continuing discussion started at https://github.com/KiCad/kicad-library/pull/1561. I don't see a better place, so why not start the discussion of connector footprints here?

How should we name the footprint libs? I shared some thoughts earlier on this at https://github.com/KiCad/Connectors_WAGO.pretty/issues/1#issuecomment-311439248 and I'll reproduce my comments here:

> Parts that fall into the category of interconnection are in the following libraries:
> Connectors* (14 libraries)
> Mechanical_Sockets
> Modules (that one may a bit of a stretch)
> Mounting_Holes
> Pin_Headers
> Socket_Strips
> Sockets
> TerminalBlocks* (2 libraries)
> Wire_Connections
> Wire_Pads
> 
> That is 24 libraries that the user could choose from. And they're scattered alphanumerically from C to W.
> 
> Let me think out loud about choosing an interconnection. Multiple vendors may have a suitable footprint. Since KiCad has a clear separation between logical (schematic) and physical (PCB), perhaps grouping by manufacturer is wrong. This means more places to look in case the user doesn't care about the vendor but is most interested in finding an interconnect by type/style/pitch/etc.
> 
> To me, this is a greater burden. I see a lot of overlap and hunting to find the desired interconnect. While I do like breaking things up a bit and can see how that can be simpler, perhaps a powerful search function is better than having a large number of libraries and only being able to see the contents of one library at a time? Naturally, this would require core developer effort.
> 
> And one smaller note. Why is is `TerminalBlocks` instead of `Terminal_Blocks`? In every other case I can see, words are separated by underscores or hyphens. This is the only example of CamelCase I see.

I believe one objective would be to bring together all of the various interconnect footprints together. Since we already have a good number of libraries that start with `Connectors`, that seems like a good place to start.

One initial question: Even with the pain of updating the repo names, is it best to make these libraries singular like we are doing with the new schematic symbol libraries? What's the conversation between singular and plural? https://github.com/KiCad/kicad-library/issues/1402#issuecomment-313975348 is the discussion for symbol libraries and I think it holds here that singular sounds better than plural.

Let's start with something like this:

| Library Name | Description | Previous Name | Notes |
| ------------------ | --------------- | --------------------- | ------------ |
| Conn_Audio | 3.5mm, RCA, XLR, Toslink, banana, etc. | |
| Conn_Card | SD, CF, SIM, etc. cards in all shapes and sizes | |
| Conn_Coaxial | BNC, SMA | |
| Conn_Computer | ISA, PCI, PCIe, SATA, NuBus | some overlap here with USB, Memory, etc.|
| Conn_Dsub | D-subminiature, male and female | |
| Conn_Edge | PCB edge connector | |
| Conn_Ethernet (or Conn_Network or Conn_RJ) | RJ45 | |
| Conn_FFC_FPC | Flex cables | |
| Conn_Video | HDMI, DVI, DisplayPort, VGA | |
| Conn_Memory | DIMM, SIMM, SODIMM | |
| Conn_Pin_Header | IDC male pin headers; THT/SMD; straight/angled; 1+ rows; optional latch | |
| Conn_Power | DC barrel jack,  | |
| Conn_Socket | IC sockets, ZIF sockets | |
| Conn_Socket_Strips | Female sockets; THT/SMD; straight/angled; 1+ rows | |
| Conn_Tab (or Conn_Blade) | Tab/blade/FastOn | |
| Conn_Terminal_Block | Screw and screwless bare wire connectors | |
| Conn_Test | JTAG, Tag-Connect | |
| Conn_USB | | what about Firewire, Thunderbolt, etc.? Conn_Computer_Peripheral is too long |
| Conn_Wire | Wire pads, testpoints | |

I dislike having a generic `Connector.pretty` repo, since it will likely turn into a wasteland, but there are so many connector types it may be the best way to go.

Edits:
1. 28 Aug - @evanshultz - Found my previous comment and included above; added Connector_Video
1. 31 Aug - @evanshultz - Removed Connector_DIMM, renamed Connector_Pin to Connector_Pin_Header and Connector_HDMI to Connector_Video, added more libs and descriptions
1. 3 Sep - @evanshultz - Change "Connector" to "Conn"

**Comment by evanshultz** [comment]
Here were some comments by @poeschlr that I brought over:

> Short note: I like Connector_Network more than Connector_Ethernet
> And another note: For connectors manufacturer specific libs make sense. (I don't think you wanted to imply to remove them, just making sure everyone is on the same page here)
> 
> I would also keep the name Connectors instead of Connector. (Otherwise all current repos need to be renamed again.)

**Comment by SchrodingersGat** [comment]
In general, I prefer to group by **function** over **manufacturer** - this is the way that the new arrangement of the symbol libs (for KiCad v5) will be implemented.

e.g.

`Connectors_Video`
`Connectors_USB`

etc.

However, many connectors are not for a single function - e.g. look at all the footprints in `Connectors_JST` or `Connectors_Hirose`

Thus, any general-purpose connector should be placed in a manufacturer library (as is currently the case).

This also reduces extreme size of footprint libraries. If all terminal blocks were in the same library, it would be immense.

**Comment by SchrodingersGat** [comment]
> We could use Conn instead of Connector to make the library names shorter

If we can work out a way to reduce breakage of library associations I would also like to make this change. However it may be more effort than it is worth...

**Comment by evanshultz** [comment]
I made some updates to the table above. Please take a look and provide feedback or update.

@SchrodingersGat 
How do we decide which footprints stay in manufacturer-specific libs, then? That seems extremely difficult/messy, if not impossible, to determine. Eliminating manufacturer libraries is the only way I can see that will make this determination straightforward.

I believe there is a reasonable way to categorize all the parts without manufacturer libraries, but it may require two levels. For example, Conn_TerminalBlocks_RightAngle or Conn_TerminalBlock_Screw?

JST's top-level categories are at http://www.jst.com/home21.html, and Hirose's are at https://www.hirose.com/product/en/. While they may make a huge slew of connectors, which we could choose to further subdivide if needed, at the highest level they both have a reasonable number of categories that all their connectors fall into. Is there a certain part or part family that is troublesome?

Would your scripts work to identify symbols using connectors, making the Connector->Conn (if we do it) easier to catch? I realize there is still effort involved which may be best spent elsewhere.

How about singular versus plural?

**Comment by SchrodingersGat** [comment]
I believe there is a reasonable way to categorize all the parts without manufacturer libraries, but it may require two levels. 

I think there is a difference here between "for-purpose" connectors (e.g. USB / HDMI) and general purpose wire-to-board connectors. We cannot group all "rectangular side entry THT connectors" together, the resulting library would be massive.

Generic connectors can serve multiple *functions* and thus will be harder to categorise...

Perhaps, a good starting point is the [DigiKey categorisation](https://www.digikey.com/products/en/connectors-interconnects/20). Based on this, I would suggest:

* Conn_Barrel
* Conn_Circular
* Conn_Coaxial
* Conn_DIN
* Conn_DSUB
* Conn_FPC
* Conn_PinHeader
* Conn_PinSocket
* Conn_Rectangular 
* ... etc ...

However these will become ungainly very fast!

Perhaps once a library becomes too large, we could make subcategories from manufacturer e.g.

* Conn_Rect_JST
* Conn_Rect_Hirose
* Conn_Rect_Harwin
* ... etc ...

If *even more* differentiation is needed, at that point we can split into part family

* Conn_Rect_JST_GH

> Would your scripts work to identify symbols using connectors, making the Connector->Conn (if we do it) easier to catch? I realize there is still effort involved which may be best spent elsewhere.

I think we can make that work.

> How about singular versus plural?

Singular, for the same reasons as the symbol libs

**Comment by SchrodingersGat** [comment]
We have now marked this repository as read-only, and new footprint contributions must be made to https://github.com/kicad/kicad-footprints
